#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/dump/home/shane/notes/ws/blog/blog
#+HUGO_SECTION: ./posts

#+TITLE: Proposal to GitHub
#+DATE: <2021-12-17>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: github

Hi Michael,

Thank you for setting up my interview with
Ganesh. I am very interested in this role as
an IDE researcher for Copilot and I'm
interested in maximising the potential of
Copilot, and its chance of survival, however
I'm going to require a bit of extra
flexibility in the role or at least the
acknowledgement of my concerns in the interest
of GitHub, not myself.

* Proposal to GitHub for a strategy of innovation for Copilot
** My timeline
*** 2016
- Built a logs and code search engine (in 2 weeks) before the ElasticSearch/LogStash/Kibana stack existed, while working as a CICD engineer.
  - I take initiative and just build what needs to be built, before people understand why it's important.
- Used it in practice for a fortune 500 (C company to correlate error and other log messages with git commits which broke HIL tests.
  - It is also a point-and-click search engine, that makes learning codebases easy.
*** 2018
- Returned to Uni to study deep learning and information retrieval. I built a GitHub code search engine before =grep.app= was a thing, with a web GUI and an emacs IDE.
*** 2019
- Created a pipeline for CodeLingo in only 1 month, which took their platform from
  an academic project to impacting a huge number
  (2000+) of GitHub organisations with automated bug-fixing.
*** 2020
- Developed a deployment pipeline for the firmware of self-driving cars for FMG.
*** 2021
- I built an IDE that utilises language models (Pen.el) 7 months before Copilot was a thing. And I had a working prototype of Pen.el after only 2 weeks.
- Built a language server that utilises language models. This is still the only one in existence, as far as I am aware.
- Invented a programming paradigm called imaginary programming, and presented at EmacsConf.
- Invented/discovered many more things such as the Imaginary Web, and created a web browser that imagines the web
- Discovered language chimeras, and built tools to utilise them.
- The list goes on and on for the discoveries I have made...
- On <2021-12-17 Fri> I had an interview for a role with GitHub for as an IDE researcher.
*** 2022 (What I will do)
- Continue expanding on Imaginary Programming
  - Haskell version of 𝑖lambda, which is already in the works.
- Continue investigating tree-sitter with NLG/natural language code-generation.
  - Incorporate that into Pen.el and Copilot
- Allow Copilot to use alternative language models, including Microsoft's large language models.
  - This will fight off competition from TabNine.
- Work on the Copilot LSP server and investigate combining it with web browsers, to create a Copilot for the web.
- Combine Copilot with Pen.el
- Continue expanding on LookingGlass, my imaginary web browser
  - Incorporate image and video generation
- Turn Copilot into a project that is innovative and ahead of the competition
- Develop peer-to-peer LM generation sharing (not prompt sharing)
- Develop peer-to-peer prompt sharing

** My perspective of the interview
I am concerned that the Codex model is not
being correctly utilised by Copilot, because
the product is trying to derive correct code
from the LMs, which is an ambitious and
laudable goal but speed and accuracy shouldn't
be of greater importance than designing a
model of human-computer interaction which
aligns more closely to the natural
capabilities of the model, which would certainly yield a
lot of innovative features for Copilot, which
I have already demonstrated in Pen.el.

That being said, the goal of creating a
brilliant code-completion tool for VSCode
needn't be scrapped -- it's certainly
possible, but this is not innovation.

I am concerned that the Copilot project will
fail to innovate enough within the next 6
months and will not be able to compete with
repl.it and TabNine. I'm about 2 years ahead
in terms of design and ambition and I can see
a dead-end for Copilot if the strategy is
merely to build a code-completion engine and
prompt-based code-refactoring tools.

I'm concerned that placing me in a the role
which restricts my ability to make discoveries
and bring them back to Copilot will sabotage
Copilot if it were my job to be a researcher
there, where I should be genuinely researching
and designing, as per the job description.

I am very interested in helping Copilot to
succeed, and building a tool with GitHub which
will benefit the maximum number of people, due
to its urgency, and I'm interested in bringing
transparency to the programming paradigm of
prompt-engineering.

Thank you for the interviews thus far and I'd
like you to consider hiring me for a research
position, not just by name but in practice,

Shane Mulligan