#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/dump/home/shane/notes/ws/blog/blog
#+HUGO_SECTION: ./posts

#+TITLE: Proposal to GitHub
#+DATE: <2021-12-17>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: github

* Proposal to GitHub for a strategy of innovation for Copilot
** Timeline
*** 2016
- Built a logs and code search engine before the ElasticSearch/LogStash/Kibana stack existed
- Used it in practice for a fortune 500 company to correlate error messages with git commits which broke HIL tests
*** 2018
- Built a GitHub code search engine before =grep.app= was a thing, with a web GUI and an emacs IDE
*** 2019
- Created a pipeline for CodeLingo in record
  time (1 month), which took their platform from
  an academic project to impacting a huge number
  (2000+) of GitHub organisations with automated bug-fixing.
*** 2020
- Developed a deployment pipeline for the firmware of self-driving cars. Utilised emacs.
*** 2021
- Built an IDE that utilises language models (Pen.el) 7 months before Copilot was a thing.
- Invented a programming paradigm called imaginary programming, and presented at EmacsConf.
- And I had a working prototype after 2 weeks.
- Invented/discovered many more things such as the Imaginary Web, and created a web browser that imagines the web
- Discovered language chimeras, and built tools to utilise them
- The list goes on and on for the discoveries I have made...
- On <2021-12-17 Fri> I had an interview for a role with GitHub for as an IDE researcher.

** The interview



** Strategy
- 6 months from now, software engineering