#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/dump/home/shane/notes/ws/blog/blog
#+HUGO_SECTION: ./posts

#+TITLE: Proposal to GitHub
#+DATE: <2021-12-17>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: github

* Proposal to GitHub for a strategy of innovation for Copilot
** Timeline
*** 2016
- Built a logs and code search engine (in 2 weeks) before the ElasticSearch/LogStash/Kibana stack existed, while working as a CICD engineer.
  - I take initiative and just build what needs to be built, before people understand why it's important.
- Used it in practice for a fortune 500 company to correlate error and other log messages with git commits which broke HIL tests.
  - It is also a point-and-click search engine, that makes learning codebases easy.
*** 2018
- Returned to Uni to study deep learning and information retrieval. I built a GitHub code search engine before =grep.app= was a thing, with a web GUI and an emacs IDE.
*** 2019
- Created a pipeline for CodeLingo in only 1 month, which took their platform from
  an academic project to impacting a huge number
  (2000+) of GitHub organisations with automated bug-fixing.
*** 2020
- Developed a deployment pipeline for the firmware of self-driving cars for FMG.
*** 2021
- I built an IDE that utilises language models (Pen.el) 7 months before Copilot was a thing. And I had a working prototype of Pen.el after only 2 weeks.
- Built a language server that utilises language models. This is still the only one in existence, as far as I am aware.
- Invented a programming paradigm called imaginary programming, and presented at EmacsConf.
- Invented/discovered many more things such as the Imaginary Web, and created a web browser that imagines the web
- Discovered language chimeras, and built tools to utilise them.
- The list goes on and on for the discoveries I have made...
- On <2021-12-17 Fri> I had an interview for a role with GitHub for as an IDE researcher.

** My perspective of the interview
- I am concerned that the Copilot project will fail to innovate enough within the next 6 months.
  - 
I'm at least 1 year ahead in terms of design.

** The interview



** Strategy
- 6 months from now, software engineering